import os
os.system('pip install colorama')
os.system('pip install pystyle')
os.system('pip install faker')
os.system('pip install telebot')
os.system('pip install telephone')
os.system('pip install faker')
os.system('pip install whois')
os.system('pip install phonenumbers')
os.system('pip install UserAgent')
os.system('pip install fake_useragent')
os.system('pip install colored')
os.system('pip install uuid')
os.system('pip install paketlib')
